language: node_js
version: 1.0

node_js:
  - node

cache: yarn

script:
  - yarn ci

deploy:
  edge: true
  provider: npm
  email: accounts@francoisbest.com
  api_key:
    secure: PSTBj9OUsHYMtI7vETHIsKybIz/NU7hpwSYtxQQ+v45eAD0FlJWgUu602kZAEUM+3/TrXwyv4yJjwRL5d08QwSebeC+NAQQ5CAetRk6pFZ6yL7Bv86NR80QR9/9SkqMzfF9wg+WRRyYBptHH3vRb+UQbHSJQwKsyP8Ah1+I48uCXwIR5padiqJT5jJqnSOcRf9EureO1fJDXwGIv9BKoyryckwFXBSt8W+90/E7m6/63uyoyWVYHPqb8VMe27FVZpl3sU0t51di863XQxtHix6Rin4V4Eaw3Z3sNMpCsM2k/r268aXNGujAoELF/veiWtsq+sQ//Qt23lqUfT+NUIGH8uU2Ji8yTa0F7HauDANO6wJYvu4oTXsWgRyKVCyuCHb214Jv04fFYFpJBpCAeF+DguH+bAEVM2PGSea1+ShzCFQByMwJVbj7i3oKZY/oDWVuYsRQPTmnwtvXaAEOYwHMzq7p1PrxI+iehXWETKuEodCoZYL4VnKdgR2HoiPiJymTd/m1UfiaoiNUtUUM+Z+9l9tuXndDh3fe0eASwOse+qtNWcVEIg8qWl08n/PI3gmVRznfTdxBo1X5uo6rWrjgthYI3ZH+gTWcy9S0CmVmr8PkJce6tHOuP5HDo3aQophXmLXSRHBZsT1pZ9gHtZphL+v8R2Uj/uoWwtbtLoQk=
  on:
    tags: true
  skip_cleanup: true

notifications:
  slack:
    rooms:
      secure: TvrOJhyRfbZeLjkepKkNpmraAnS7uHhfDESrFWKrmwCNj5KmnKr3IcA9tAnR1B9XU5mt2qehINahQ0oWzkdCsaopNJdVSQ8NYufyf1rGJpIPfb2tLhJsbTR6UDk3IzYNAEW/TzNj7lhwvGryNcp98wu3w6yOrhsxW6/l5l88lZV9wFF00E5uwJ1ZGibGY78Lw4sn8sSFR/Qf0+l5tz8q4MsZZFvKnneJJqeqwn4yClt86/Dtz3fPnkMP+I9BDF7YxU35o9Sh8Og/TTUzr6BEQHDxjQEmoewml4VuH+fYx005zq5Y75L46czUO6PdZAeR/Z+xT0a9Rle9AXpofNfR2o1PF2cWyJTEBLiCwwUPI4MJ4OlG8tb2ehKs44BDgZGrh/V9VqUKGgfGYqSFGvzFu3agRLHhc5785g8pma2g+ipz9uNUtSoIJiS9Y2icUaAYWkYeDF8Q5ghvF6dFV/ccw1oh2QtGzw+EYubLG7zl+wMaG19QirPKO/6nBV+l68WELUS/5vU8W+QJS63OrD/zuMC3hHlPN2GPu0/IXQGdBrpn433pSu5hTGNHXOWI30POjF8cWN6l43bhNFU+3KcNHDd+WLNxZ9KAXGSg3Hw1A2byGN2dM/qqdURLwvBGJluJ6CJUwlEe8fhN6ZQYOCjn1JuA8eYcHS9xp3FW2SEMeK8=
    on_success: change
    on_failure: always
